# Binomial Distributions
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

In [1]:
# import numpy
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### 1. A fair coin flip produces heads

In [2]:
# simulate 1 million tests of one fair coin flip
# remember, the output of these tests are the # successes, or # heads
# the first parameter is # of coin
# the second parameter is  fair coin,  p(H) = 0.5
# the 3rd parameter is how many flips
tests = np.random.binomial(1, 0.5, int(1e6))
print(tests)
# proportion of tests that produced heads
(tests == 1).mean()

[1 0 1 ... 1 1 0]


0.500618

### 2. Five fair coin flips produce exactly one head

In [7]:
# simulate 1 million tests of five fair coin flips
tests = np.random.binomial(5, 0.5, int(1e6))
print(tests)

# proportion of tests that produced 1 head, 4 tail
(tests == 1).mean()

[1 3 1 ... 3 3 3]


0.15626

### 3. Ten fair coin flips produce exactly four heads

In [4]:
# simulate 1 million tests of ten fair coin flips
tests = np.random.binomial(10, 0.5, int(1e6))
print(tests)

# proportion of tests that produced 4 heads, 6 tails
(tests == 4).mean()

[5 5 4 ... 5 3 5]


0.205582

### 4. Five biased coin flips with P(H) = 0.8 produce exactly five heads

In [5]:
# simulate 1 million tests of five biased coin flips
tests = np.random.binomial(5, 0.8, int(1e6))
print(tests)

# proportion of tests that produced 5 heads, 0 tail
(tests == 5).mean()

[4 4 2 ... 2 5 4]


0.327142

### 5. Ten biased coin flips with P(H) = 0.15 produce at least 3 heads

In [6]:
# simulate 1 million tests of ten biased coin flips
tests = np.random.binomial(10, 0.15, int(1e6))
print(tests)

# proportion of tests that produced at least 3 heads, 7 tails
(tests >= 3).mean()

[0 2 0 ... 1 2 0]


0.179457