# Coin Flips and Die Rolls

In [2]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [17]:
# simulate 1 million tests of two fair coin flips
# the first parameter set each coin has two possible outcome
# the size function para1: 100000 time, with 2 coins
tests = np.random.randint(2, size=(int(1e6), 2))
print(tests)
# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

[[1 1]
 [1 1]
 [0 1]
 ...
 [1 0]
 [0 0]
 [0 1]]
[2 2 1 ... 1 0 1]


0.250265

### 2. Three fair coin flips produce exactly one head

In [21]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))
print(tests)
# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)
# proportion of tests that produced exactly one head and two tails (1,1)

print(test_sums == 2)
(test_sums == 2).mean()

[[1 1 1]
 [0 0 1]
 [1 1 0]
 ...
 [1 1 0]
 [0 0 1]
 [0 0 0]]
[3 1 2 ... 2 1 0]
[False False  True ...  True False False]


0.374843

n coins with k heads (k < n), what is the p for get k heads
n!/(k! * (n-k)!)  * p^k * (1-p)^(n-k)    <=== this includes the weighted coins

In [23]:
print((test_sums == 0).mean())
print((test_sums == 1).mean())
print((test_sums == 2).mean())
print((test_sums == 3).mean())

0.125315
0.375587
0.374843
0.124255


### 3. Three bias coin flips with P(H) = 0.6 produce exactly one head

In [25]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], size=(int(1e6), 3), p=[0.6, 0.4])
print(tests)

# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)

# proportion of tests that produced exactly one head and two tail
(test_sums == 2).mean()

[[0 0 0]
 [0 0 1]
 [0 0 1]
 ...
 [1 1 0]
 [1 0 1]
 [1 1 1]]
[0 1 1 ... 2 2 3]


0.28744

### 4. A die rolls an even number

In [9]:
# simulate 1 million tests of one die roll
tests = np.random.choice(np.arange(1, 7), size=int(1e6))
print(tests)
# proportion of tests that produced an even number
(tests % 2 == 0).mean()

[6 2 3 ... 1 5 5]


0.50007

### 5. Two dice roll a double

In [31]:
# simulate the first million die rolls
first = np.random.choice(np.arange(6), size=int(1e6))

# simulate the second million die rolls
second = np.random.choice(np.arange(6), size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.16746