In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
# outcome of one coin flip
# np.random.randint(0,2) #include 0, 1, exclude 2
np.random.randint(2)

1

In [24]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 1, 1, ..., 0, 1, 0])

In [39]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.4937

In [112]:
# outcome of one coin flip, and there are two possible outcome 0 and 1
np.random.choice([0, 1])

0

In [56]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 0, 1, ..., 0, 0, 1])

In [113]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4981

In [21]:
# outcomes of ten thousand biased coin flips with p(0)=0.8 and p(1)=0.2
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 0, 0, ..., 0, 0, 0])

In [126]:
# mean outcome of ten thousand biased coin flips: because now heads (0) will appear 80% of the time
# tail (1) will appear 20% of the time
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.1969